services:

  # FastAPI Application
  fastapi:
    build:
      context: ..
      dockerfile: docker/arabic_legal/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.app
    volumes:
      - fastapi_data:/app/assets/data
    networks:
      - backend
    restart: always
    depends_on:
      pgvector:
        condition: service_healthy

  pgvector:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql
    env_file:
      - ./env/.env.postgres
    restart: always
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U arabic-legal" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

    # Prometheus PostgreSQL exporter for postgres metrics
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    ports:
      - "9187:9187"
    env_file:
      - ./env/.env.postgres-exporter
    networks:
      - backend
    restart: always
    depends_on:
      - pgvector

volumes:
  pgvector_data:
  fastapi_data:

networks:
  backend:
